baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My Hugo Portfolio'
theme: basic
params: 
  author: Shamika
  description: My Portfolio Site
  gh_url: "https://api.github.com/users" 
  gh_user: "shamikae"
permalinks: 
  posts: "/posts/:year/:month/:slug/"